### ISSUE TITLE
Does SpectralCluster work with XVector?

### ISSUE THREAD

**Issue by minhnq97** [wq2012/SpectralCluster#10]
Firstly, I want to say thank you for your great work.

As the question, I just see the experiment of Spectral Cluster with i-Vector and d-Vector at [this](https://google.github.io/speaker-id/publications/LstmDiarization/resources/icassp2018_diarization_poster.pdf). However, i've never seen any experiment with x-Vector. 
Have you ever done it? If yes, is x-Vector + Spectral Cluster  better than i-Vector + Spectral Cluster?

Thank you!

**Comment by wq2012** [comment]
The "d" in d-vector means "deep neural networks".

x-vector is also based on deep neural networks, and it's essentially JHU's version of d-vector. They call it "x" likely because they used data augmentation techniques based on reverberating noises for training. But in fact d-vector also uses similar data augmentation, which at Google is called "Multistyle Training (MTR)".

So anything that works for d-vector should also work for x-vector.
